name: macOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-14  # Apple Silicon runner (macOS 14)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Build macOS App
        run: |
          xcodebuild \
            -project Web/Web.xcodeproj \
            -scheme Web \
            -configuration Release \
            -archivePath build/Web.xcarchive \
            archive

      - name: Export .app
        run: |
          mkdir -p build/App
          cp -R build/Web.xcarchive/Products/Applications/Web.app build/App/

      - name: Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: Web-macOS-App
          path: build/App/Web.app