name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: 选择 Xcode
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # Step 3: 编译 macOS app
      - name: Build macOS App
        run: |
          xcodebuild \
            -project Web.xcodeproj \
            -scheme Web \
            -configuration Release \
            -archivePath build/Web.xcarchive \
            archive

      # Step 4: 导出 .app
      - name: Export .app
        run: |
          mkdir -p build/App
          cp -R build/Web.xcarchive/Products/Applications/Web.app build/App/

      # Step 5: 上传 .app 到 artifact
      - name: Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: Web-macOS-App
          path: build/App/Web.app
